[package]
name = "aleo-prover"
version = "0.3.0"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#snarkvm = { path = "../../src/snarkVM" }
snarkvm = { git = "https://github.com/HarukaMa/snarkVM.git", rev = "cfb283e3" }
#snarkos = { path = "../../src/snarkOS" }
#snarkos-storage = { path = "../../src/snarkOS/storage" }
snarkos = { git = "https://github.com/HarukaMa/snarkOS.git", rev = "8ca00e64" }
snarkos-storage = { git = "https://github.com/HarukaMa/snarkOS.git", rev = "8ca00e64" }
rand = "0.8.5"
num_cpus = "1.13.1"
structopt = "0.3.26"
rayon = "1.5.1"
anyhow = "1.0.53"
tracing = "0.1.30"
tracing-subscriber = "0.3.8"
tokio-stream = "0.1.8"
futures = "0.3.21"
futures-util = "0.3.21"
crossbeam = "0.8.1"
bytes = "1.1.0"
bincode = "1.3.3"
byteorder = "1.4.3"
ansi_term = "0.12.1"
redis = "*"
uuid = { version = "0.8.2", features = ["v4"] }
serde_json = "*"
serde = {version = "*", features = ["derive"]}


[dependencies.tokio]
version = "1.16.1"
features = [
    "rt-multi-thread",
    "macros",
    "sync",
]

[dependencies.tokio-util]
version = "0.7.0"
features = ["codec"]

[features]
cuda = ["snarkvm/cuda"]

[profile.dev]
opt-level = 1
debug-assertions = false

[profile.release]
opt-level = 3
debug = 1
lto = true
codegen-units = 1
panic = "abort"
